name: android_overlay
description: A Flutter plugin for displaying an overlay on top of the Android system UI.
version: 0.0.2
homepage: https://github.com/Mobile-Artificial-Intelligence/android_overlay

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.danemadsen.android_overlay
        pluginClass: AndroidOverlayPlugin
